version: '1'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "8000:8000"
    networks:
      - front-tier

  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    entrypoint: uvicorn --app-dir app main:app --host 0.0.0.0 --port 8000 --log-config=config/logging_config.yaml
    expose:
      - "8000"
    depends_on:
      - redis
    networks:
      - back-tier
      - front-tier
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
    networks:
      - back-tier

networks:
  front-tier: {}
  back-tier: {}